// <auto-generated />
using Desafio_Fiap.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio_Fiap.Api.Data.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desafio_Fiap.Api.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("turma");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("INT")
                        .HasColumnName("ano");

                    b.HasKey("Id");

                    b.ToTable("turma", (string)null);
                });

            modelBuilder.Entity("Desafio_Fiap.Api.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("nome");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("CHAR")
                        .HasColumnName("senha");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("aluno", (string)null);
                });

            modelBuilder.Entity("aluno_turma", b =>
                {
                    b.Property<int>("aluno_id")
                        .HasColumnType("int");

                    b.Property<int>("class_id")
                        .HasColumnType("int");

                    b.HasKey("aluno_id", "class_id");

                    b.HasIndex("class_id");

                    b.ToTable("aluno_turma");
                });

            modelBuilder.Entity("aluno_turma", b =>
                {
                    b.HasOne("Desafio_Fiap.Api.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("aluno_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Desafio_Fiap.Api.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
